; PlatformIO Project Configuration File
[platformio]
src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib
data_dir = firmware/data
test_dir = firmware/test

default_envs = RP2350


[env]
; Settings applied to all environments
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.filesystem = littlefs
board_build.filesystem_size = 64k
monitor_speed = 115200
lib_deps =
	infineon/XENSIV 3D Magnetic Sensor TLx493D@^1.1.2
	adafruit/Adafruit NeoPixel@^1.15.5
	bxparks/AceButton@^1.10.1

; Add the VID/PID you want your space mouse to use
board_build.core = earlephilhower
; board_build.arduino.earlephilhower.usb_vid =
; board_build.arduino.earlephilhower.usb_pid =
; board_build.arduino.earlephilhower.usb_manufacturer =
board_build.arduino.earlephilhower.usb_product = CAD Mouse MK2


[env:RP2040]
; Inherits settings from [env]
board = seeed_xiao_rp2040
build_unflags =  -Os ; disable GCC optimization for size, we want speed
build_flags =
	-I firmware/include ; include directory for header files
	-Ofast ; enable GCC optimization for speed
	-DUSE_TINYUSB ; use TinyUSB stack instead of Arduino's USB stack
	-DBOARD_RP2040 ; define the board type for conditional compilation


[env:RP2350]
; Inherits settings from [env]
board = seeed_xiao_rp2350
build_unflags =  -Os ; disable GCC optimization for size, we want speed
build_flags = 
	-I firmware/include ; include directory for header files
	-Ofast ; enable GCC optimization for speed
	-DUSE_TINYUSB ; use TinyUSB stack instead of Arduino's USB stack
	-DBOARD_RP2350 ; define the board type for conditional compilation
